var OA_output = new Array(); 
OA_output['1'] = '';
OA_output['1'] += "<"+"span><"+"script type=\'text/javascript\'><"+"!--// <"+"![CDATA[\n";
OA_output['1'] += "/* openads=http://simplyguide.com/c/www/delivery bannerid=47 zoneid=25 source= */\n";
OA_output['1'] += "// ]]> --><"+"/script><"+"script type=\"text/javascript\"><"+"!--\n";
OA_output['1'] += "google_ad_client = \"ca-pub-7825705102693166\";\n";
OA_output['1'] += "/* cyberciti.biz-top 728x90 */\n";
OA_output['1'] += "google_ad_slot = \"3400670370\";\n";
OA_output['1'] += "google_ad_width = 728;\n";
OA_output['1'] += "google_ad_height = 90;\n";
OA_output['1'] += "//-->\n";
OA_output['1'] += "<"+"/script>\n";
OA_output['1'] += "<"+"script type=\"text/javascript\"\n";
OA_output['1'] += "src=\"http://pagead2.googlesyndication.com/pagead/show_ads.js\">\n";
OA_output['1'] += "<"+"/script><"+"script type=\'text/javascript\' src=\'http://simplyguide.com/c/www/delivery/ag.php\'><"+"/script><"+"/span><"+"div id=\'beacon_f265f61c4b\' style=\'position: absolute; left: 0px; top: 0px; visibility: hidden;\'><"+"img src=\'http://simplyguide.com/c/www/delivery/lg.php?bannerid=47&amp;campaignid=16&amp;zoneid=25&amp;loc=1&amp;referer=http%3A%2F%2Fbash.cyberciti.biz%2Fguide%2FWhat_is_Linux_Shell&amp;cb=f265f61c4b\' width=\'0\' height=\'0\' alt=\'\' style=\'width: 0px; height: 0px;\' /><"+"/div>\n";
OA_output['2'] = '';
OA_output['2'] += "<"+"span><"+"script type=\'text/javascript\'><"+"!--// <"+"![CDATA[\n";
OA_output['2'] += "/* openads=http://simplyguide.com/c/www/delivery bannerid=47 zoneid=25 source= */\n";
OA_output['2'] += "// ]]> --><"+"/script><"+"script type=\"text/javascript\"><"+"!--\n";
OA_output['2'] += "google_ad_client = \"ca-pub-7825705102693166\";\n";
OA_output['2'] += "/* cyberciti.biz-top 728x90 */\n";
OA_output['2'] += "google_ad_slot = \"3400670370\";\n";
OA_output['2'] += "google_ad_width = 728;\n";
OA_output['2'] += "google_ad_height = 90;\n";
OA_output['2'] += "//-->\n";
OA_output['2'] += "<"+"/script>\n";
OA_output['2'] += "<"+"script type=\"text/javascript\"\n";
OA_output['2'] += "src=\"http://pagead2.googlesyndication.com/pagead/show_ads.js\">\n";
OA_output['2'] += "<"+"/script><"+"script type=\'text/javascript\' src=\'http://simplyguide.com/c/www/delivery/ag.php\'><"+"/script><"+"/span><"+"div id=\'beacon_09954f0882\' style=\'position: absolute; left: 0px; top: 0px; visibility: hidden;\'><"+"img src=\'http://simplyguide.com/c/www/delivery/lg.php?bannerid=47&amp;campaignid=16&amp;zoneid=25&amp;loc=1&amp;referer=http%3A%2F%2Fbash.cyberciti.biz%2Fguide%2FWhat_is_Linux_Shell&amp;cb=09954f0882\' width=\'0\' height=\'0\' alt=\'\' style=\'width: 0px; height: 0px;\' /><"+"/div>\n";
OA_output['26'] = '';
OA_output['26'] += "<"+"span><"+"script type=\'text/javascript\'><"+"!--// <"+"![CDATA[\n";
OA_output['26'] += "/* openads=http://simplyguide.com/c/www/delivery bannerid=48 zoneid=26 source= */\n";
OA_output['26'] += "// ]]> --><"+"/script><"+"script type=\"text/javascript\"><"+"!--\n";
OA_output['26'] += "google_ad_client = \"ca-pub-7825705102693166\";\n";
OA_output['26'] += "/* Cyberciti.biz.Vertical.Bottom */\n";
OA_output['26'] += "google_ad_slot = \"9465804393\";\n";
OA_output['26'] += "google_ad_width = 120;\n";
OA_output['26'] += "google_ad_height = 240;\n";
OA_output['26'] += "//-->\n";
OA_output['26'] += "<"+"/script>\n";
OA_output['26'] += "<"+"script type=\"text/javascript\"\n";
OA_output['26'] += "src=\"http://pagead2.googlesyndication.com/pagead/show_ads.js\">\n";
OA_output['26'] += "<"+"/script><"+"script type=\'text/javascript\' src=\'http://simplyguide.com/c/www/delivery/ag.php\'><"+"/script><"+"/span><"+"div id=\'beacon_6e6f0953e8\' style=\'position: absolute; left: 0px; top: 0px; visibility: hidden;\'><"+"img src=\'http://simplyguide.com/c/www/delivery/lg.php?bannerid=48&amp;campaignid=17&amp;zoneid=26&amp;loc=1&amp;referer=http%3A%2F%2Fbash.cyberciti.biz%2Fguide%2FWhat_is_Linux_Shell&amp;cb=6e6f0953e8\' width=\'0\' height=\'0\' alt=\'\' style=\'width: 0px; height: 0px;\' /><"+"/div>\n";
OA_output['4'] = '';
OA_output['4'] += "<"+"span><"+"script type=\'text/javascript\'><"+"!--// <"+"![CDATA[\n";
OA_output['4'] += "/* openads=http://simplyguide.com/c/www/delivery bannerid=53 zoneid=27 source= */\n";
OA_output['4'] += "// ]]> --><"+"/script><"+"script type=\"text/javascript\"><"+"!--\n";
OA_output['4'] += "google_ad_client = \"ca-pub-7825705102693166\";\n";
OA_output['4'] += "/* Cyberciti.biz-300x250 */\n";
OA_output['4'] += "google_ad_slot = \"7895531150\";\n";
OA_output['4'] += "google_ad_width = 300;\n";
OA_output['4'] += "google_ad_height = 250;\n";
OA_output['4'] += "//-->\n";
OA_output['4'] += "<"+"/script>\n";
OA_output['4'] += "<"+"script type=\"text/javascript\"\n";
OA_output['4'] += "src=\"http://pagead2.googlesyndication.com/pagead/show_ads.js\">\n";
OA_output['4'] += "<"+"/script><"+"script type=\'text/javascript\' src=\'http://simplyguide.com/c/www/delivery/ag.php\'><"+"/script><"+"/span><"+"div id=\'beacon_c3b95f8367\' style=\'position: absolute; left: 0px; top: 0px; visibility: hidden;\'><"+"img src=\'http://simplyguide.com/c/www/delivery/lg.php?bannerid=53&amp;campaignid=20&amp;zoneid=27&amp;loc=1&amp;referer=http%3A%2F%2Fbash.cyberciti.biz%2Fguide%2FWhat_is_Linux_Shell&amp;cb=c3b95f8367\' width=\'0\' height=\'0\' alt=\'\' style=\'width: 0px; height: 0px;\' /><"+"/div>\n";
OA_output['5'] = '';
OA_output['5'] += "<"+"span><"+"script type=\'text/javascript\'><"+"!--// <"+"![CDATA[\n";
OA_output['5'] += "/* openads=http://simplyguide.com/c/www/delivery bannerid=53 zoneid=27 source= */\n";
OA_output['5'] += "// ]]> --><"+"/script><"+"script type=\"text/javascript\"><"+"!--\n";
OA_output['5'] += "google_ad_client = \"ca-pub-7825705102693166\";\n";
OA_output['5'] += "/* Cyberciti.biz-300x250 */\n";
OA_output['5'] += "google_ad_slot = \"7895531150\";\n";
OA_output['5'] += "google_ad_width = 300;\n";
OA_output['5'] += "google_ad_height = 250;\n";
OA_output['5'] += "//-->\n";
OA_output['5'] += "<"+"/script>\n";
OA_output['5'] += "<"+"script type=\"text/javascript\"\n";
OA_output['5'] += "src=\"http://pagead2.googlesyndication.com/pagead/show_ads.js\">\n";
OA_output['5'] += "<"+"/script><"+"script type=\'text/javascript\' src=\'http://simplyguide.com/c/www/delivery/ag.php\'><"+"/script><"+"/span><"+"div id=\'beacon_dfc7c59844\' style=\'position: absolute; left: 0px; top: 0px; visibility: hidden;\'><"+"img src=\'http://simplyguide.com/c/www/delivery/lg.php?bannerid=53&amp;campaignid=20&amp;zoneid=27&amp;loc=1&amp;referer=http%3A%2F%2Fbash.cyberciti.biz%2Fguide%2FWhat_is_Linux_Shell&amp;cb=dfc7c59844\' width=\'0\' height=\'0\' alt=\'\' style=\'width: 0px; height: 0px;\' /><"+"/div>\n";
OA_output['25'] = '';
OA_output['25'] += "<"+"span><"+"script type=\'text/javascript\'><"+"!--// <"+"![CDATA[\n";
OA_output['25'] += "/* openads=http://simplyguide.com/c/www/delivery bannerid=47 zoneid=25 source= */\n";
OA_output['25'] += "// ]]> --><"+"/script><"+"script type=\"text/javascript\"><"+"!--\n";
OA_output['25'] += "google_ad_client = \"ca-pub-7825705102693166\";\n";
OA_output['25'] += "/* cyberciti.biz-top 728x90 */\n";
OA_output['25'] += "google_ad_slot = \"3400670370\";\n";
OA_output['25'] += "google_ad_width = 728;\n";
OA_output['25'] += "google_ad_height = 90;\n";
OA_output['25'] += "//-->\n";
OA_output['25'] += "<"+"/script>\n";
OA_output['25'] += "<"+"script type=\"text/javascript\"\n";
OA_output['25'] += "src=\"http://pagead2.googlesyndication.com/pagead/show_ads.js\">\n";
OA_output['25'] += "<"+"/script><"+"script type=\'text/javascript\' src=\'http://simplyguide.com/c/www/delivery/ag.php\'><"+"/script><"+"/span><"+"div id=\'beacon_16e80b7373\' style=\'position: absolute; left: 0px; top: 0px; visibility: hidden;\'><"+"img src=\'http://simplyguide.com/c/www/delivery/lg.php?bannerid=47&amp;campaignid=16&amp;zoneid=25&amp;loc=1&amp;referer=http%3A%2F%2Fbash.cyberciti.biz%2Fguide%2FWhat_is_Linux_Shell&amp;cb=16e80b7373\' width=\'0\' height=\'0\' alt=\'\' style=\'width: 0px; height: 0px;\' /><"+"/div>\n";
OA_output['8'] = '';

OA_output['9'] = '';
OA_output['9'] += "<"+"a href=\'http://simplyguide.com/c/www/delivery/ck.php?oaparams=2__bannerid=9__zoneid=9__cb=d6cea62e74__oadest=http%3A%2F%2Fad.doubleclick.net%2Fjump%2FN3691.140644.0517859818421%2FB3799835.3%3Bsz%3D640x480\' target=\'_blank\'><"+"img src=\'http://ad.doubleclick.net/ad/N3691.140644.0517859818421/B3799835.3;sz=640x480\' width=\'640\' height=\'480\' alt=\'\' title=\'\' border=\'0\' /><"+"/a><"+"div id=\'beacon_d6cea62e74\' style=\'position: absolute; left: 0px; top: 0px; visibility: hidden;\'><"+"img src=\'http://simplyguide.com/c/www/delivery/lg.php?bannerid=9&amp;campaignid=4&amp;zoneid=9&amp;loc=http%3A%2F%2Fbash.cyberciti.biz%2Fguide%2FWhat_is_Linux_Shell&amp;referer=http%3A%2F%2Fin.search.yahoo.com%2Fsearch%3Fvc%3D%26p%3Dwhat+is+sheel+scripting+in+unix%253F%26toggle%3D1%26cop%3Dmss%26ei%3DUTF-8%26fr%3Dyfp-t-704&amp;cb=d6cea62e74\' width=\'0\' height=\'0\' alt=\'\' style=\'width: 0px; height: 0px;\' /><"+"/div>\n";
OA_output['27'] = '';
OA_output['27'] += "<"+"span><"+"script type=\'text/javascript\'><"+"!--// <"+"![CDATA[\n";
OA_output['27'] += "/* openads=http://simplyguide.com/c/www/delivery bannerid=53 zoneid=27 source= */\n";
OA_output['27'] += "// ]]> --><"+"/script><"+"script type=\"text/javascript\"><"+"!--\n";
OA_output['27'] += "google_ad_client = \"ca-pub-7825705102693166\";\n";
OA_output['27'] += "/* Cyberciti.biz-300x250 */\n";
OA_output['27'] += "google_ad_slot = \"7895531150\";\n";
OA_output['27'] += "google_ad_width = 300;\n";
OA_output['27'] += "google_ad_height = 250;\n";
OA_output['27'] += "//-->\n";
OA_output['27'] += "<"+"/script>\n";
OA_output['27'] += "<"+"script type=\"text/javascript\"\n";
OA_output['27'] += "src=\"http://pagead2.googlesyndication.com/pagead/show_ads.js\">\n";
OA_output['27'] += "<"+"/script><"+"script type=\'text/javascript\' src=\'http://simplyguide.com/c/www/delivery/ag.php\'><"+"/script><"+"/span><"+"div id=\'beacon_7f582fea13\' style=\'position: absolute; left: 0px; top: 0px; visibility: hidden;\'><"+"img src=\'http://simplyguide.com/c/www/delivery/lg.php?bannerid=53&amp;campaignid=20&amp;zoneid=27&amp;loc=1&amp;referer=http%3A%2F%2Fbash.cyberciti.biz%2Fguide%2FWhat_is_Linux_Shell&amp;cb=7f582fea13\' width=\'0\' height=\'0\' alt=\'\' style=\'width: 0px; height: 0px;\' /><"+"/div>\n";
OA_output['10'] = '';

OA_output['11'] = '';

OA_output['18'] = '';
OA_output['18'] += "<"+"a href=\'http://simplyguide.com/c/www/delivery/ck.php?oaparams=2__bannerid=31__zoneid=18__cb=ca4724158a__oadest=http%3A%2F%2Fwww.cyberciti.biz%2Ftips%2Fnixcraft-faq-pdf-collection-now-available-to-all.html%3Futm_source%3Dcyberciti.biz%26utm_campaign%3Dmay09_468x60_1%26utm_medium%3Dtop_banner\' target=\'_blank\'><"+"img src=\'http://files.cyberciti.biz/assets/s/may_9_2010/nixcraft_pdf_468x60_1.png\' width=\'468\' height=\'60\' alt=\'Love Linux Enjoy Sys Admin? Download eBook\' title=\'Love Linux Enjoy Sys Admin? Download eBook\' border=\'0\' /><"+"/a><"+"div id=\'beacon_ca4724158a\' style=\'position: absolute; left: 0px; top: 0px; visibility: hidden;\'><"+"img src=\'http://simplyguide.com/c/www/delivery/lg.php?bannerid=31&amp;campaignid=8&amp;zoneid=18&amp;loc=http%3A%2F%2Fbash.cyberciti.biz%2Fguide%2FWhat_is_Linux_Shell&amp;referer=http%3A%2F%2Fin.search.yahoo.com%2Fsearch%3Fvc%3D%26p%3Dwhat+is+sheel+scripting+in+unix%253F%26toggle%3D1%26cop%3Dmss%26ei%3DUTF-8%26fr%3Dyfp-t-704&amp;cb=ca4724158a\' width=\'0\' height=\'0\' alt=\'\' style=\'width: 0px; height: 0px;\' /><"+"/div>\n";
OA_output['28'] = '';

OA_output['20'] = '';

OA_output['22'] = '';
OA_output['22'] += "<"+"script src=\"http://bs.serving-sys.com/BurstingPipe/adServer.bs?cn=rsb&c=28&pli=1445798&PluID=0&e=0&w=640&h=480&ord=%n&ncu=$$%c$$\"><"+"/script><"+"noscript>\n";
OA_output['22'] += "<"+"a href=\"%chttp://bs.serving-sys.com/BurstingPipe/BannerRedirect.asp?FlightID=1445798&Page=&PluID=0&Pos=8436\" target=\"_blank\"><"+"img src=\"http://bs.serving-sys.com/BurstingPipe/BannerSource.asp?FlightID=1445798&Page=&PluID=0&Pos=8436\" border=0 width=640 height=480><"+"/a>\n";
OA_output['22'] += "<"+"/noscript><"+"div id=\'beacon_cb8d1cbe35\' style=\'position: absolute; left: 0px; top: 0px; visibility: hidden;\'><"+"img src=\'http://simplyguide.com/c/www/delivery/lg.php?bannerid=38&amp;campaignid=4&amp;zoneid=22&amp;loc=1&amp;referer=http%3A%2F%2Fbash.cyberciti.biz%2Fguide%2FWhat_is_Linux_Shell&amp;cb=cb8d1cbe35\' width=\'0\' height=\'0\' alt=\'\' style=\'width: 0px; height: 0px;\' /><"+"/div>\n";
OA_output['23'] = '';

OA_output['24'] = '';

OA_output['29'] = '';

OA_output['30'] = '';

OA_output['31'] = '';
OA_output['31'] += "<"+"span><"+"script type=\'text/javascript\'><"+"!--// <"+"![CDATA[\n";
OA_output['31'] += "/* openads=http://simplyguide.com/c/www/delivery bannerid=53 zoneid=27 source= */\n";
OA_output['31'] += "// ]]> --><"+"/script><"+"script type=\"text/javascript\"><"+"!--\n";
OA_output['31'] += "google_ad_client = \"ca-pub-7825705102693166\";\n";
OA_output['31'] += "/* Cyberciti.biz-300x250 */\n";
OA_output['31'] += "google_ad_slot = \"7895531150\";\n";
OA_output['31'] += "google_ad_width = 300;\n";
OA_output['31'] += "google_ad_height = 250;\n";
OA_output['31'] += "//-->\n";
OA_output['31'] += "<"+"/script>\n";
OA_output['31'] += "<"+"script type=\"text/javascript\"\n";
OA_output['31'] += "src=\"http://pagead2.googlesyndication.com/pagead/show_ads.js\">\n";
OA_output['31'] += "<"+"/script><"+"script type=\'text/javascript\' src=\'http://simplyguide.com/c/www/delivery/ag.php\'><"+"/script><"+"/span><"+"div id=\'beacon_b5f41f3f80\' style=\'position: absolute; left: 0px; top: 0px; visibility: hidden;\'><"+"img src=\'http://simplyguide.com/c/www/delivery/lg.php?bannerid=53&amp;campaignid=20&amp;zoneid=27&amp;loc=1&amp;referer=http%3A%2F%2Fbash.cyberciti.biz%2Fguide%2FWhat_is_Linux_Shell&amp;cb=b5f41f3f80\' width=\'0\' height=\'0\' alt=\'\' style=\'width: 0px; height: 0px;\' /><"+"/div>\n";
OA_output['32'] = '';

